import Files from '@/components/Files'
import TopMenuContainer from '@/components/TopMenuContainer'
import { Box, Stack } from '@chakra-ui/react'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box color="textPrimary" background="backgroundPrimary" height="100vh" padding="40px">
          <Stack rowGap="20px">
            <TopMenuContainer />
            <Files />
          </Stack>
        </Box>
      </main>
    </>
  )
}
