import Logo from '@/components/reusables/Logo'
import { Box, Flex, Text } from '@chakra-ui/react'
import { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'

const Login: NextPage = () => {
  return (
    <>
      <Head>
        <title>DriveBox</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main>
        <Box
          background="primaryBlue"
          height="100vh"
        >
          <Box position="absolute" left="20px" top="20px">
            <Logo
              textColor="white"
              logoColor="white"
            />
          </Box>
        </Box>
      </main>
    </>
  )
}

export default Login